package com.elsevier.transform;

import java.util.HashMap;

public class CountryCodeMap {

	public static HashMap<String, String> codes = new HashMap<String, String>();
	
	static {
		codes.put("acx", "Ascension");
		codes.put("and", "Andorra");
		codes.put("are", "United Arab Emirates");
		codes.put("afg", "Afghanistan");
		codes.put("atg", "Antigua and Barbuda");
		codes.put("aia", "Anguilla");
		codes.put("alb", "Albania");
		codes.put("arm", "Armenia");
		codes.put("ant", "Netherlands Antilles");
		codes.put("ago", "Angola");
		codes.put("ata", "Antarctica");
		codes.put("arg", "Argentina");
		codes.put("asm", "American Samoa");
		codes.put("aut", "Austria");
		codes.put("aus", "Australia");
		codes.put("abw", "Aruba");
		codes.put("aze", "Azerbaijan");
		codes.put("bih", "Bosnia and Herzegovina");
		codes.put("brb", "Barbados");
		codes.put("bgd", "Bangladesh");
		codes.put("bel", "Belgium");
		codes.put("bfa", "Burkina Faso");
		codes.put("bgr", "Bulgaria");
		codes.put("bhr", "Bahrain");
		codes.put("bdi", "Burundi");
		codes.put("ben", "Benin");
		codes.put("bmu", "Bermuda");
		codes.put("brn", "Brunei Darussalam");
		codes.put("bol", "Bolivia");
		codes.put("bra", "Brazil");
		codes.put("bhs", "Bahamas");
		codes.put("btn", "Bhutan");
		codes.put("bux", "Burma");
		codes.put("bvt", "Bouvet Island");
		codes.put("bwa", "Botswana");
		codes.put("blr", "Belarus");
		codes.put("blz", "Belize");
		codes.put("can", "Canada");
		codes.put("cck", "Cocos (Keeling) Islands");
		codes.put("cod", "Democratic Republic Congo");
		codes.put("caf", "Central African Republic");
		codes.put("cog", "Congo");
		codes.put("che", "Switzerland");
		codes.put("civ", "Cote d'Ivoire");
		codes.put("cok", "Cook Islands");
		codes.put("chl", "Chile");
		codes.put("cmr", "Cameroon");
		codes.put("chn", "China");
		codes.put("col", "Colombia");
		codes.put("cri", "Costa Rica");
		codes.put("csx", "Czechoslovakia");
		codes.put("ctx", "Canton and Enderburry Islands");
		codes.put("cub", "Cuba");
		codes.put("cpv", "Cape Verde");
		codes.put("cxr", "Christmas Island");
		codes.put("cyp", "Cyprus");
		codes.put("cze", "Czech Republic");
		codes.put("ddx", "Germany (Democratic Republic, DDR)");
		codes.put("deu", "Germany");
		codes.put("dji", "Djibouti");
		codes.put("dnk", "Denmark");
		codes.put("dma", "Dominica");
		codes.put("dom", "Dominican Republic");
		codes.put("dza", "Algeria");
		codes.put("ecu", "Ecuador");
		codes.put("est", "Estonia");
		codes.put("egy", "Egypt");
		codes.put("esh", "Western Sahara");
		codes.put("eri", "Eritrea");
		codes.put("esp", "Spain");
		codes.put("eth", "Ethiopia");
		codes.put("fin", "Finland");
		codes.put("fji", "Fiji");
		codes.put("flk", "Falkland Islands (Malvinas)");
		codes.put("fsm", "Federated States of Micronesia");
		codes.put("fro", "Faroe Islands");
		codes.put("fra", "France");
		codes.put("gab", "Gabon");
		codes.put("gbr", "United Kingdom");
		codes.put("grd", "Grenada");
		codes.put("geo", "Georgia");
		codes.put("guf", "French Guiana");
		codes.put("gha", "Ghana");
		codes.put("gib", "Gibraltar");
		codes.put("grl", "Greenland");
		codes.put("gmb", "Gambia");
		codes.put("gin", "Guinea");
		codes.put("glp", "Guadeloupe");
		codes.put("gnq", "Equatorial Guinea");
		codes.put("grc", "Greece");
		codes.put("sgs", "South Georgia and the South Sandwich Islands");
		codes.put("gtm", "Guatemala");
		codes.put("gum", "Guam");
		codes.put("gnb", "Guinea-Bissau");
		codes.put("guy", "Guyana");
		codes.put("hkg", "Hong Kong");
		codes.put("hmd", "Heard Island and McDonald Islands");
		codes.put("hnd", "Honduras");
		codes.put("hrv", "Croatia");
		codes.put("hti", "Haiti");
		codes.put("hun", "Hungary");
		codes.put("idn", "Indonesia");
		codes.put("irl", "Ireland");
		codes.put("isr", "Israel");
		codes.put("ind", "India");
		codes.put("iot", "British Indian Ocean Territory");
		codes.put("irq", "Iraq");
		codes.put("irn", "Iran");
		codes.put("isl", "Iceland");
		codes.put("ita", "Italy");
		codes.put("jam", "Jamaica");
		codes.put("jor", "Jordan");
		codes.put("jpn", "Japan");
		codes.put("jtx", "Johnston Island");
		codes.put("ken", "Kenya");
		codes.put("kgz", "	Kyrgyzstan");
		codes.put("khm", "Cambodia");
		codes.put("kir", "Kiribati");
		codes.put("com", "Comoros");
		codes.put("kna", "Saint Kitts and Nevis");
		codes.put("prk", "North Korea");
		codes.put("kor", "South Korea");
		codes.put("kwt", "Kuwait");
		codes.put("cym", "Cayman Islands");
		codes.put("kaz", "Kazakhstan");
		codes.put("lao", "Laos");
		codes.put("lbn", "Lebanon");
		codes.put("lca", "Saint Lucia");
		codes.put("lie", "Liechtenstein");
		codes.put("lka", "Sri Lanka");
		codes.put("lbr", "Liberia");
		codes.put("lso", "Lesotho");
		codes.put("ltu", "Lithuania");
		codes.put("lux", "Luxembourg");
		codes.put("lva", "Latvia");
		codes.put("lby", "Libyan Arab Jamahiriya");
		codes.put("mar", "Morocco");
		codes.put("mco", "Monaco");
		codes.put("mda", "Moldova");
		codes.put("mne", "Montenegro");
		codes.put("mdg", "Madagascar");
		codes.put("mhl", "Marshall Islands");
		codes.put("mix", "Midway Islands");
		codes.put("mkd", "Macedonia");
		codes.put("mli", "Mali");
		codes.put("mmr", "Myanmar");
		codes.put("mng", "Mongolia");
		codes.put("mac", "Macao");
		codes.put("mnp", "Northern Mariana Islands");
		codes.put("mtq", "Martinique");
		codes.put("mrt", "Mauritania");
		codes.put("msr", "Montserrat");
		codes.put("mlt", "Malta");
		codes.put("mus", "Mauritius");
		codes.put("mdv", "Maldives");
		codes.put("mwi", "Malawi");
		codes.put("mex", "Mexico");
		codes.put("mys", "Malaysia");
		codes.put("moz", "Mozambique");
		codes.put("nam", "Namibia");
		codes.put("ncl", "New Caledonia");
		codes.put("ner", "Niger");
		codes.put("nfk", "Norfolk Island");
		codes.put("nga", "Nigeria");
		codes.put("nic", "Nicaragua");
		codes.put("nld", "Netherlands");
		codes.put("nor", "Norway");
		codes.put("npl", "Nepal");
		codes.put("nqx", "Dronning Maud Land");
		codes.put("nru", "Nauru");
		codes.put("ntx", "Neutral Zone");
		codes.put("niu", "Niue");
		codes.put("nzl", "New Zealand");
		codes.put("omn", "Oman");
		codes.put("pan", "Panama");
		codes.put("pcx", "Pacific Islands");
		codes.put("per", "Peru");
		codes.put("pyf", "French Polynesia");
		codes.put("png", "Papua New Guinea");
		codes.put("phl", "Philippines");
		codes.put("pak", "Pakistan");
		codes.put("pol", "Poland");
		codes.put("spm", "Saint Pierre and Miquelon");
		codes.put("pcn", "Pitcairn");
		codes.put("pri", "Puerto Rico");
		codes.put("pse", "Palestine");
		codes.put("prt", "Portugal");
		codes.put("pux", "United States Miscellaneous Pacific Islands");
		codes.put("plw", "Palau");
		codes.put("pry", "Paraguay");
		codes.put("qat", "Qatar");
		codes.put("reu", "Reunion");
		codes.put("rou", "Romania");
		codes.put("srb", "Serbia");
		codes.put("rus", "Russian Federation");
		codes.put("rwa", "Rwanda");
		codes.put("sau", "Saudi Arabia");
		codes.put("slb", "Solomon Islands");
		codes.put("syc", "Seychelles");
		codes.put("sdn", "Sudan");
		codes.put("swe", "Sweden");
		codes.put("sgp", "Singapore");
		codes.put("shn", "Saint Helena");
		codes.put("svn", "Slovenia");
		codes.put("sjm", "Svalbard and Jan Mayen");
		codes.put("svk", "Slovakia");
		codes.put("sle", "Sierra Leone");
		codes.put("smr", "San Marino");
		codes.put("sen", "Senegal");
		codes.put("som", "Somalia");
		codes.put("sur", "Suriname");
		codes.put("stp", "Sao Tome and Principe");
		codes.put("sux", "Russia");
		codes.put("slv", "El Salvador");
		codes.put("syr", "Syrian Arab Republic");
		codes.put("swz", "Swaziland");
		codes.put("tca", "Turks and Caicos Islands");
		codes.put("tcd", "Chad");
		codes.put("atf", "French Southern Territories");
		codes.put("tgo", "Togo");
		codes.put("tha", "Thailand");
		codes.put("tjk", "Tajikistan");
		codes.put("tkl", "Tokelau");
		codes.put("tls", "Timor-Leste");
		codes.put("tkm", "Turkmenistan");
		codes.put("tun", "Tunisia");
		codes.put("ton", "Tonga");
		codes.put("tur", "Turkey");
		codes.put("tto", "Trinidad and Tobago");
		codes.put("tuv", "Tuvalu");
		codes.put("twn", "Taiwan");
		codes.put("tza", "Tanzania");
		codes.put("ukr", "Ukraine");
		codes.put("uga", "Uganda");
		codes.put("umi", "United States Minor Outlying Islands");
		codes.put("unx", "United Nations");
		codes.put("usa", "United States");
		codes.put("ury", "Uruguay");
		codes.put("uzb", "Uzbekistan");
		codes.put("vat", "Vatican City State");
		codes.put("vct", "Saint Vincent and the Grenadines");
		codes.put("ven", "Venezuela");
		codes.put("vgb", "Virgin Islands (British)");
		codes.put("vir", "Virgin Islands (U.S.)");
		codes.put("vnm", "Viet Nam");
		codes.put("vut", "Vanuatu");
		codes.put("wlf", "Wallis and Futuna");
		codes.put("wkx", "Wake Island");
		codes.put("wsm", "Samoa");
		codes.put("ydx", "Yemen, Democratic People's Republic");
		codes.put("yem", "Yemen");
		codes.put("myt", "Mayotte");
		codes.put("yux", "Yugoslavia");
		codes.put("zaf", "South Africa");
		codes.put("zmb", "Zambia");
		codes.put("zrx", "Zaire");
		codes.put("zwe", "Zimbabwe");
	}
}
